name: Consumer workflow

on:
  push:
    branches: [ main ]  
    paths:
      - dotnetConsumer/**
  pull_request:
    branches: [ main ]
    paths:
      - dotnetConsumer/**

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: docker login
      env:        
        CR_USERNAME: ${{ secrets.CR_USERNAME }}
        PAT: ${{ secrets.PAT }}
      run: |
        echo $PAT | docker login https://docker.pkg.github.com -u $CR_USERNAME --password-stdin
    - name: build .NET Consumer Docker image 
      run: |
        docker build -f ./dotnetConsumer/Dockerfile --pull --rm -t docker.pkg.github.com/${{ secrets.CR_USERNAME }}/dapr-demo/dotnet-consumer:${GITHUB_SHA} ./dotnetConsumer